# Generated by Django 5.2.7 on 2025-11-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nac', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='autor_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.autor'),
        ),
    ]
