# Generated by Django 5.2.7 on 2025-11-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_autor_post_autor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
