# Generated by Django 5.2.7 on 2025-11-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor_fk',
            new_name='autor',
        ),
    ]
